version: 0.0
os: linux
files:
  - source: /
    destination: /home
hooks:
  BeforeInstall:
    - location: script.sh
      runas: root
  ApplicationStart:
    - location: start_app.sh
      runas: root
