apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployement
  labels:
    app: python-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
        - name: python-test
          image: 494473211790.dkr.ecr.ap-south-1.amazonaws.com/1ankit_test:latest
          ports:
          - containerPort: 80
      
      
      
      
      
      
