apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  type: NodePort
  ports:
   - targetPort: 3000
     port: 3000
     nodePort: 30001
  selector:
     app: grafana
     
