apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: ClusterIP
  ports:
   - targetPort: 3000
     port: 3000
  selector:
     app.kubernetes.io/instance: grafana
     app.kubernetes.io/name: grafana
     type: grafana
